### ISSUE TITLE
Sync from container

### ISSUE THREAD

**Issue by Bajix** [CircleCI-Public/aws-s3-orb#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to use `aws-ecr/build-and-push-image` to build my frontend and then to be able to use `aws-s3/sync` to be able to sync my build directory from said image into s3 before trigging cloudfront invalidation.

**Describe alternatives you've considered**
Because I can only use `aws-s3/sync` to sync from a workspace, I resort to building my frontend within my workspace and forego building this part as a docker image. 

**Additional context**
Docker layer image caching is substantially faster than restoring/storing a dependency cache. Being able to sync directly from my built image will be a substantially faster workflow and will create better consistency as everything can be managed via a parallel `aws-ecr/build-and-push-image` and a follow up helm install/upgrade + `aws-s3/sync` + cloudfront invalidation

**Comment by KyleTryon** [comment]
Hello @Bajix,

Sorry for the long delay in response here. I am not sure which version of the orb you were using but I believe the issue may have been resolved since then. Take a look at the current Sync orb if you are still interested and let us know. We will close this for now.

https://circleci.com/developer/orbs/orb/circleci/aws-s3#commands-sync
