### ISSUE TITLE
Question: How to dynamically set the "to" field in /sync

### ISSUE THREAD

**Issue by tmadison-gpsw** [CircleCI-Public/aws-s3-orb#25]
I am curious how to dynamically set the "to" field https://github.com/CircleCI-Public/aws-s3-orb/blob/master/src/examples/sync_and_copy.yml#L16 as we would like to change buckets etc based on `CIRCLE_SHA1` etc.

Thanks

**Comment by gmemstr** [comment]
@tmadison-gpsw You could store the bucket name as an environment variable in a prior step, and use that in the argument.

**Comment by tymik** [comment]
~@gmemstr I'm just doing it that way and it doesn't work - when I'm passing the variable to the orb as a parameter from the job and I pass ENV VAR to the job in workflow, it doesn't evaluate the variable, just puts it there as a string.
Doing the test by placing the ENV VAR directly in the job instead of passing it as the parameter and the issue remains the same.~

~It results in:~

```
#!/bin/bash -eo pipefail
aws s3 sync \
  dist s3://${STAGING_AWS_S3_BUCKET}  \
  --acl private \
--cache-control "max-age=86400"
--delete



The user-provided path dist does not exist.

Exited with code exit status 255
CircleCI received exit code 255
```

Apparently I got fixated on the target and the issue was with the source, apologies for raising the issue that's not there.
